service: go-serverless-api
frameworkVersion: ">=1.28.0"
provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}
functions:
  api:
    handler: bin/main
    events:
      - http:
          path: /ping
          method: GET

package:
  patterns:
    - "!*/**"
    - bin/main
